// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sample struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sub                  *Sample_Sub `protobuf:"bytes,3,opt,name=sub,proto3" json:"sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_dc7b2f31afc8b545, []int{0}
}
func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (dst *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(dst, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sample) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sample) GetSub() *Sample_Sub {
	if m != nil {
		return m.Sub
	}
	return nil
}

type Sample_Sub struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sample_Sub) Reset()         { *m = Sample_Sub{} }
func (m *Sample_Sub) String() string { return proto.CompactTextString(m) }
func (*Sample_Sub) ProtoMessage()    {}
func (*Sample_Sub) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_dc7b2f31afc8b545, []int{0, 0}
}
func (m *Sample_Sub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample_Sub.Unmarshal(m, b)
}
func (m *Sample_Sub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample_Sub.Marshal(b, m, deterministic)
}
func (dst *Sample_Sub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample_Sub.Merge(dst, src)
}
func (m *Sample_Sub) XXX_Size() int {
	return xxx_messageInfo_Sample_Sub.Size(m)
}
func (m *Sample_Sub) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample_Sub.DiscardUnknown(m)
}

var xxx_messageInfo_Sample_Sub proto.InternalMessageInfo

func (m *Sample_Sub) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sample_Sub) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Sample)(nil), "proto.Sample")
	proto.RegisterType((*Sample_Sub)(nil), "proto.Sample.Sub")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SampleServiceClient is the client API for SampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SampleServiceClient interface {
	GetSample(ctx context.Context, in *Sample, opts ...grpc.CallOption) (*Sample, error)
}

type sampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewSampleServiceClient(cc *grpc.ClientConn) SampleServiceClient {
	return &sampleServiceClient{cc}
}

func (c *sampleServiceClient) GetSample(ctx context.Context, in *Sample, opts ...grpc.CallOption) (*Sample, error) {
	out := new(Sample)
	err := c.cc.Invoke(ctx, "/proto.SampleService/GetSample", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleServiceServer is the server API for SampleService service.
type SampleServiceServer interface {
	GetSample(context.Context, *Sample) (*Sample, error)
}

func RegisterSampleServiceServer(s *grpc.Server, srv SampleServiceServer) {
	s.RegisterService(&_SampleService_serviceDesc, srv)
}

func _SampleService_GetSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sample)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).GetSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SampleService/GetSample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).GetSample(ctx, req.(*Sample))
	}
	return interceptor(ctx, in, info, handler)
}

var _SampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SampleService",
	HandlerType: (*SampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSample",
			Handler:    _SampleService_GetSample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample.proto",
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor_sample_dc7b2f31afc8b545) }

var fileDescriptor_sample_dc7b2f31afc8b545 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x32, 0xe9, 0xf9,
	0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25,
	0x99, 0xf9, 0x79, 0xc5, 0x10, 0x45, 0x4a, 0x35, 0x5c, 0x6c, 0xc1, 0x60, 0x4d, 0x42, 0x7c, 0x5c,
	0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c,
	0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x32,
	0x17, 0x73, 0x71, 0x69, 0x92, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x20, 0xc4, 0x08, 0x3d,
	0x88, 0x7e, 0xbd, 0xe0, 0xd2, 0xa4, 0x20, 0x90, 0xac, 0x94, 0x26, 0x17, 0x73, 0x70, 0x69, 0x12,
	0x31, 0xe6, 0x19, 0xbd, 0x60, 0xe4, 0xe2, 0x85, 0x68, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0x15, 0xba, 0xc6, 0xc8, 0xc5, 0xe9, 0x9e, 0x5a, 0x02, 0x75, 0x13, 0x2f, 0x8a, 0x15, 0x52, 0xa8,
	0x5c, 0xa5, 0x55, 0x8c, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x5a, 0xcc, 0xa8, 0xc4, 0xaf, 0x5f, 0x66,
	0xa8, 0x0f, 0xf1, 0xbc, 0x7e, 0x52, 0x7e, 0x4a, 0xa5, 0x15, 0xa3, 0x56, 0x94, 0x94, 0x92, 0x30,
	0x92, 0x68, 0x41, 0x62, 0x51, 0x09, 0x58, 0x06, 0xe4, 0xc4, 0x28, 0x79, 0x21, 0x59, 0x14, 0xb9,
	0x92, 0x0c, 0xfd, 0xea, 0xcc, 0x94, 0x5a, 0xfd, 0xea, 0xe2, 0xd2, 0x24, 0xbd, 0xcc, 0x94, 0xda,
	0x28, 0x0d, 0x25, 0x45, 0x2c, 0x9a, 0x51, 0x15, 0x41, 0x8c, 0x12, 0x14, 0x42, 0xb6, 0x1c, 0xa4,
	0x20, 0x4a, 0x58, 0x48, 0x10, 0x59, 0x08, 0xe4, 0xd3, 0xda, 0x24, 0x36, 0xb0, 0xd3, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xd3, 0xce, 0x39, 0xa4, 0x01, 0x00, 0x00,
}
